name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0, lts
        version: 10.x
    - name: Install deps
      run: yarn
    - name: Test
      run: CI=1 yarn test
    - name: Build
      run: yarn build
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
        # Create incremental commit instead of doing push force
        keep_history: true
        # Build directory to deploy
        build_dir: build
      env:
       GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
